[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"
edition = "2021"

[dependencies]
liblzma-sys = { path = "../liblzma-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.2"
