name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
          - os: ubuntu-latest
            rust: stable
            static: yes
          - os: ubuntu-latest
            rust: beta
          - os: ubuntu-latest
            rust: nightly
          - os: macos-latest
            rust: stable
          - os: macos-latest
            rust: stable
            static: yes
          - os: windows-latest
            rust: stable-i686-msvc
          - os: windows-latest
            rust: stable-x86_64-msvc
          - os: windows-latest
            rust: stable-x86_64-msvc
            static: yes
          - os: windows-latest
            rust: stable-x86_64-msvc
            static: yes
            crt_static: yes
          - os: windows-latest
            rust: stable-i686-gnu
          - os: windows-latest
            rust: stable-x86_64-gnu
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Rust (rustup)
      run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
      shell: bash
    - name: Set crt-static
      if: matrix.crt_static == 'yes'
      run: echo RUSTFLAGS=-Ctarget-feature=+crt-static >> $GITHUB_ENV
      shell: bash
    - name: Set static
      if: matrix.static == 'yes'
      run: echo LZMA_API_STATIC=1 >> $GITHUB_ENV
      shell: bash
    - run: |
        cargo test --no-default-features
        cargo clean -p liblzma -p liblzma-sys
    - run: |
        cargo test --features parallel
        cargo clean -p liblzma -p liblzma-sys
    - run: |
        cargo test --features bindgen
        cargo clean -p liblzma -p liblzma-sys
    # thin-lto and fat-lto feature required use clang as a linker, but linux default linker is gcc. so exclude thin-lto and fat-lto.
    - run: |
        cargo test --features parallel,static
        cargo clean -p liblzma -p liblzma-sys
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
    - run: |
        cargo test --all-features
        cargo clean -p liblzma -p liblzma-sys
      if: ${{ !startsWith(matrix.os, 'ubuntu') }}
    - run: |
        cargo run --manifest-path systest/Cargo.toml
        cargo clean -p liblzma -p liblzma-sys
      if: matrix.static == 'yes'
    - run: cargo run --manifest-path systest/Cargo.toml --features bindgen
      if: matrix.static == 'yes'


  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Rust
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - run: cargo fmt -- --check
