name: Publish Rust crate

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
      - if: startsWith(github.ref, 'refs/tags/liblzma-sys')
        name: Publish liblzma-sys crate
        run: cargo publish
        working-directory: liblzma-sys
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_API_KEY }}"
      - if: !startsWith(github.ref, 'refs/tags/liblzma-sys') && startsWith(github.ref, 'refs/tags/liblzma')
        name: Publish liblzma crate
        run: cargo publish
        working-directory: .
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_API_KEY }}"
