name: Build Webassembly
on: [push, pull_request]

jobs:
  test:
    name: Test WebAssembly
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly-2025-05-16 # Pin nightly rust version because emscripten target not worked
        target:
          - wasm32-unknown-emscripten
          - wasm32-unknown-unknown
          - wasm32-wasip1
        include:
          - target: wasm32-unknown-emscripten
            container: emscripten/emsdk:latest
          - target: wasm32-unknown-unknown
            container: ghcr.io/portable-network-archive/wasi-sdk-gh-actions:wasi-sdk-22
          - target: wasm32-wasip1
            container: ghcr.io/portable-network-archive/wasi-sdk-gh-actions:wasi-sdk-22

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.rust }}
      - if: ${{ startsWith(matrix.target, 'wasm32-wasi') }}
        name: Setup wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          github_token: ${{ github.token }}
      - if: ${{ startsWith(matrix.target, 'wasm32-wasi') }}
        name: Run test
        run: |
          cargo test --target ${{ matrix.target }} --features wasm
      - if: ${{ endsWith(matrix.target, 'unknown') }}
        name: Run test
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall -y --force wasm-bindgen-cli
          cargo test --target ${{ matrix.target }} --features wasm --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For ease GitHub API rate limits
      - name: Run test
        if: ${{ startsWith(matrix.target, 'wasm32-unknown-emscripten') }}
        run: |
          cargo test --target ${{ matrix.target }} --features wasm -- --skip standard_files
        env:
          RUSTFLAGS: "-C link-args=-sINITIAL_MEMORY=128MB"
